-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 22, Failures: 4, Errors: 0, Skipped: 1, Time elapsed: 5.449 s <<< FAILURE! - in TestSuite
Testlogin(com.testNg.Test.TestDepends)  Time elapsed: 0.097 s  <<< FAILURE!
java.lang.AssertionError: null
	at com.testNg.Test.TestDepends.Testlogin(TestDepends.java:12)

TestDataOut(com.testNg.Test.TestException)  Time elapsed: 0.097 s  <<< FAILURE!
org.testng.TestException: 

Method TestException.TestDataOut(int, int)[pri:0, instance:com.testNg.Test.TestException@10bea4] should have thrown an exception of type class java.lang.ArithmeticException

TestDataOut(com.testNg.Test.TestException)  Time elapsed: 0.002 s  <<< FAILURE!
org.testng.TestException: 

Method TestException.TestDataOut(int, int)[pri:0, instance:com.testNg.Test.TestException@10bea4] should have thrown an exception of type class java.lang.ArithmeticException

TestOutTimes(com.testNg.Test.TestOutTime)  Time elapsed: 1.903 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.testNg.Test.TestOutTime.TestOutTimes() didn't finish within the time-out 2000

